name: ⚙️ Compile

on:
  workflow_call:
  workflow_dispatch:

jobs:
  # ----------------------------------------
  # 🏗️ Compile
  # ----------------------------------------
  compile:
    name: 🏗️ Compile
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_TOKEN || github.token }}

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🏗️ Build
        uses: ./.github/actions/build-node
